---

zrc:
  scheme: http
  host: localhost
  port: 8000
  auth:
    client_id: demo
    secret: demo
    user_id: pytest
    user_representation: pytest

drc:
  scheme: http
  host: localhost
  port: 8001
  auth:
    client_id: demo
    secret: demo
    user_id: pytest
    user_representation: pytest

ztc:
  scheme: http
  host: localhost
  port: 8002
  auth:
    client_id: demo
    secret: demo
    user_id: pytest
    user_representation: pytest

brc:
  scheme: http
  host: localhost
  port: 8003
  auth:
    client_id: demo
    secret: demo
    user_id: pytest
    user_representation: pytest

orc:
  scheme: http
  host: localhost
  port: 8010
  # auth:
  #   secret: orc-super-secret-key

nc:
  scheme: http
  host: localhost
  port: 8004
  auth:
    client_id: demo
    secret: demo
    user_id: pytest
    user_representation: pytest

ac:
  scheme: http
  host: localhost
  port: 8005
  auth:
    client_id: demo
    secret: demo
    user_id: pytest
    user_representation: pytest
