---

zrc:
  scheme: http
  host: localhost
  port: 10000

ztc:
  scheme: http
  host: localhost
  port: 9000

orc:
  scheme: http
  host: localhost
  port: 8000

drc:
  scheme: http
  host: localhost
  port: 8001
