version: '3.4'

services:
  zrc.vng:
    volumes:
      - ${WORKSPACE}/fixtures/docker/zrc.json:/app/fixtures/zrc.json
      - zrc_logs:/app/log

  drc.vng:
    volumes:
      - ${WORKSPACE}/fixtures/docker/drc.json:/app/fixtures/drc.json
      - drc_logs:/app/log

  ztc.vng:
    volumes:
      - ${WORKSPACE}/fixtures/docker/ztc.json:/app/fixtures/ztc.json
      - ztc_logs:/app/log

  brc.vng:
    volumes:
      - ${WORKSPACE}/fixtures/docker/brc.json:/app/fixtures/brc.json
      - brc_logs:/app/log

  orc.vng:
    volumes:
      - orc_logs:/app/log

  nrc.vng:
    volumes:
      - ${WORKSPACE}/fixtures/docker/nrc.json:/app/fixtures/nrc.json
      - nrc_logs:/app/log

  ac.vng:
    volumes:
      - ${WORKSPACE}/fixtures/docker/ac.json:/app/fixtures/ac.json
      - ac_logs:/app/log

  tests:
    build:
      context: ./
    volumes:
      - ${WORKSPACE}/reports:/testenv/reports
    depends_on:
      - zrc.vng
      - drc.vng
      - ztc.vng
      - brc.vng
      - orc.vng
      - nrc.vng
      - ac.vng

volumes:
  zrc_logs:
  drc_logs:
  ztc_logs:
  brc_logs:
  orc_logs:
  nrc_logs:
  ac_logs:
