# Inspired by https://docs.docker.com/compose/django/

# This is for development purposes ONLY. Do NOT run this in production with
# the same SECRET_KEYs.

version: '3.4'

services:
  # databases
  zrc_db:
    image: mdillon/postgis:10
    volumes:
      - zrc_postgres_data:/var/lib/postgresql/data

  drc_db:
    image: postgres:10
    volumes:
      - drc_postgres_data:/var/lib/postgresql/data

  ztc_db:
    image: postgres:10
    volumes:
      - ztc_postgres_data:/var/lib/postgresql/data

  brc_db:
    image: postgres:10
    volumes:
      - brc_postgres_data:/var/lib/postgresql/data

  orc_db:
    image: postgres:10
    volumes:
      - orc_postgres_data:/var/lib/postgresql/data

  nrc_db:
    image: postgres:10
    volumes:
      - nrc_postgres_data:/var/lib/postgresql/data

  ac_db:
    image: postgres:10
    volumes:
      - ac_postgres_data:/var/lib/postgresql/data

  # task queues
  nrc_rabbitmq:
    image: rabbitmq:3.7-alpine

  # web
  zrc.vng:
    image: vngr/gemma-zrc:0.16.0
    environment:
      - DJANGO_SETTINGS_MODULE=zrc.conf.docker
      - SECRET_KEY=c1zqz%y-s-$$63ca_abc8dmfjno#&pk!wy8k9f8c*4w@(whxy1n'
      - DB_HOST=zrc_db
      - IS_HTTPS=0
    ports:
      - 8000:8000
    depends_on:
      - zrc_db

  drc.vng:
    image: vngr/gemma-drc:0.13.2
    environment:
      - DJANGO_SETTINGS_MODULE=drc.conf.docker
      - SECRET_KEY=h1kluf9r2yhcfr_i!fqb!srx=!u@!^b_gdl54=h0n15j34*+#=
      - DB_HOST=drc_db
      - IS_HTTPS=0
      - SENDFILE_BACKEND=sendfile.backends.simple
    volumes:
      - drc_media:/app/private-media
    ports:
      - 8001:8000
    depends_on:
      - drc_db

  ztc.vng:
    image: vngr/gemma-ztc:0.13.0
    environment:
      - DJANGO_SETTINGS_MODULE=ztc.conf.docker
      - SECRET_KEY=)lwxn07vp1+ru=yf^n+v4l&ij24l3vhhitw9vk4=0ix14ibmfj
      - DB_HOST=ztc_db
      - SITE_ID=2
    ports:
      - 8002:8000
    depends_on:
      - ztc_db

  brc.vng:
    image: vngr/gemma-brc:0.11.0
    environment:
      - DJANGO_SETTINGS_MODULE=brc.conf.docker
      - SECRET_KEY=dah&lsnfb^oymv*32)dr^(c9h1-chspxac%!2t=$$&g*b(spzu-
      - DB_HOST=brc_db
      - IS_HTTPS=0
    ports:
      - 8003:8000
    depends_on:
      - brc_db

  orc.vng:
    image: vngr/gemma-orc:latest
    environment:
      - DJANGO_SETTINGS_MODULE=orc.conf.docker
      - SECRET_KEY=)lwxn07vp1+ru=yf^n+v4l&ij24l3vhhitw9vk4=0ix14ibmfj
      - DB_HOST=orc_db
    ports:
      - 8010:8000
    depends_on:
      - orc_db

  nrc.vng:
    image: vngr/gemma-notifications:0.6.3
    environment:
      - DJANGO_SETTINGS_MODULE=notifications.conf.docker
      - SECRET_KEY=rt@lin*q6@wy)xd**5#xz)1p@sqcfj*@w77wn-in2+1zq6*a)m
      - DB_HOST=nrc_db
      - IS_HTTPS=0
      - PUBLISH_BROKER_URL=amqp://guest:guest@nrc_rabbitmq:5672/%2F
      - CELERY_BROKER_URL=amqp://guest:guest@nrc_rabbitmq:5672//
      - CELERY_RESULT_BACKEND=amqp://guest:guest@nrc_rabbitmq:5672//
    ports:
      - 8004:8000
    depends_on:
      - nrc_db
      - nrc_rabbitmq

  ac.vng:
    image: vngr/gemma-autorisatiecomponent:0.2.5
    environment:
      - DJANGO_SETTINGS_MODULE=ac.conf.docker
      - SECRET_KEY=8u9chcd4g1%i5z)u@s6#c#0u%s_gggx*915w(yzrf#awezmu^i
      - DB_HOST=ac_db
    ports:
      - 8005:8000
    depends_on:
      - ac_db

volumes:
  zrc_postgres_data:
  drc_postgres_data:
  drc_media:
  ztc_postgres_data:
  brc_postgres_data:
  orc_postgres_data:
  nrc_postgres_data:
  ac_postgres_data:
