version: '3.4'

services:
  zrc.vng:
    volumes:
      - ${WORKSPACE}/fixtures:/app/fixtures
      - zrc_logs:/app/log
    environment:
      ZTC_JWT_SECRET: zrc-to-ztc
  drc.vng:
    volumes:
      - ${WORKSPACE}/fixtures:/app/fixtures
      - drc_logs:/app/log
    environment:
      ZTC_JWT_SECRET: drc-to-ztc
      ZRC_JWT_SECRET: drc-to-zrc
  ztc.vng:
    volumes:
      - ${WORKSPACE}/fixtures:/app/fixtures
      - ztc_logs:/app/log
  brc.vng:
    volumes:
      - brc_logs:/app/log
  orc.vng:
    volumes:
      - orc_logs:/app/log

  tests:
    build:
      context: ./
    volumes:
      - ${WORKSPACE}/reports:/testenv/reports
    depends_on:
      - zrc.vng
      - drc.vng
      - ztc.vng
      - brc.vng
      - orc.vng

volumes:
  zrc_logs:
  drc_logs:
  ztc_logs:
  brc_logs:
  orc_logs:
