version: '3.4'

services:
  tests:
    build:
      context: ./
    volumes:
      - ${WORKSPACE}/reports:/testenv/reports
    depends_on:
      - zrc.vng
      - drc.vng
      - ztc.vng
      - brc.vng
      - orc.vng
