version: '3.4'

services:
  ztc.vng:
    volumes:
      - ${WORKSPACE}/fixtures:/app/fixtures

  tests:
    build:
      context: ./
    volumes:
      - ${WORKSPACE}/reports:/testenv/reports
    depends_on:
      - zrc.vng
      - drc.vng
      - ztc.vng
      - orc.vng
