version: '3.4'

services:
  zrc.vng:
    volumes:
      - ${WORKSPACE}/fixtures:/app/fixtures
      - zrc_logs:/app/log

  drc.vng:
    volumes:
      - ${WORKSPACE}/fixtures:/app/fixtures
      - drc_logs:/app/log

  ztc.vng:
    volumes:
      - ${WORKSPACE}/fixtures:/app/fixtures
      - ztc_logs:/app/log

  brc.vng:
    volumes:
      - ${WORKSPACE}/fixtures:/app/fixtures
      - brc_logs:/app/log

  orc.vng:
    volumes:
      - orc_logs:/app/log

  nc.vng:
    volumes:
      - ${WORKSPACE}/fixtures:/app/fixtures
      - nc_logs:/app/log
  ac.vng:
    volumes:
      - ${WORKSPACE}/fixtures:/app/fixtures
      - ac_logs:/app/log

  tests:
    build:
      context: ./
    volumes:
      - ${WORKSPACE}/reports:/testenv/reports
    depends_on:
      - zrc.vng
      - drc.vng
      - ztc.vng
      - brc.vng
      - orc.vng
      - nc.vng
      - ac.vng

volumes:
  zrc_logs:
  drc_logs:
  ztc_logs:
  brc_logs:
  orc_logs:
  nc_logs:
  ac_logs:
